version: "3.10"

services:
  db:
    container_name: chroma_db
    image: chromadb/chroma:latest
    volumes:
      - chroma-data:/chroma/chroma
    restart: unless-stopped
    networks:
      - inner
  
  inference:
    build:
      context: ./inference
      dockerfile: Dockerfile
    container_name: inference
    command: uvicorn clip:app --port 8040
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      inference/.env.dist
    networks:
      - inner

  main:
    build:
      context: ./main
      dockerfile: Dockerfile
    container_name: main_gateway
    command: uvicorn main:app --port 8080 --workers 4
    restart: unless-stopped
    depends_on:
      - db
      - inference
    env_file:
      - main/.env.dist
    ports:
      - "8080:8000"
    networks:
      - inner

volumes:
  chroma-data:
    driver: local

networks:
  inner:
    driver: bridge
