version: "3.10"

services:
  db:
    container_name: chroma_db
    image: chromadb/chroma:latest
    volumes:
      - chroma-data:/chroma/chroma
    restart: unless-stopped
    ports:
      - "8000:8000"
  
  inference:
    build:
      context: ./inference
      dockerfile: Dockerfile
    container_name: inference
    command: uvicorn clip:app --port 8040
    restart: unless-stopped
    volumes:
      - inference-model-data:/app/model_data
    depends_on:
      - db
    env_file:
      - inference/.env.dist
    ports:
      - "8040:8040"

  main:
    build:
      context: ./main
      dockerfile: Dockerfile
    container_name: main_gateway
    command: uvicorn main:app --port 8080 --workers 4
    restart: unless-stopped
    volumes:
      - main-model-data:/app/model_data
    depends_on:
      - db
      - inference
    env_file:
      - main/.env.dist
    ports:
      - "8080:8080"

volumes:
  chroma-data:
    driver: local
  inference-model-data:
    driver: local
  main-model-data:
    driver: local
