version: "3.10"

services:
  db:
    image: chromadb/chroma:latest
    container_name: chromadb
    volumes:
      - chroma-data:/chroma/chroma
    restart: unless-stopped
    ports:
      - "8000:8000"
 
  cache:
    image: memcached:latest
    container_name: memcached
    ports:
      - "11211:11211"
    restart: always

  encode:
    build:
      context: ./inference
      dockerfile: Dockerfile
    container_name: inference-encode
    command: uvicorn main:app --host "0.0.0.0" --port 80 --log-config=log_conf.yaml
    restart: unless-stopped
    volumes:
      - inference-model-data:/app/model_data
    env_file:
      - inference/.env.dist
    ports:
      - "8040:80"

  search:
    build:
      context: ./inference
      dockerfile: Dockerfile
    container_name: inference-search
    command: uvicorn main:app --host "0.0.0.0" --port 80 --log-config=log_conf.yaml
    restart: unless-stopped
    volumes:
      - inference-model-data:/app/model_data
    env_file:
      - inference/.env.dist
    ports:
      - "8050:80"

  main:
    build:
      context: ./main
      dockerfile: Dockerfile
    container_name: api-gateway
    command: uvicorn main:app --host "0.0.0.0" --port 80
    restart: unless-stopped
    volumes:
      - main-model-data:/app/model_data
    depends_on:
      - db
      - encode
      - search
      - cache
    env_file:
      - main/.env.dist
    ports:
      - "80:80"

volumes:
  chroma-data:
    driver: local
  inference-model-data:
    driver: local
  main-model-data:
    driver: local
