version: "3.10"

services:
  db:
    container_name: chroma_db
    image: chromadb/chroma:latest
    ports:
      - "8080:8000"
    volumes:
      - chroma-data:/chroma/chroma
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/v1/heartbeat" ]
      interval: 30s
      timeout: 10s
      retries: 3
  
  inference:
    build:
      context: ./inference
      dockerfile: Dockerfile
    container_name: inference
    command: uvicorn clip:app --port 8000
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      inference/.env.dist
    ports:
      - "8040:8000"

  main:
    build:
      context: ./main
      dockerfile: Dockerfile
    container_name: main_gateway
    command: uvicorn main:app --port 8000 --workers 4
    restart: unless-stopped
    depends_on:
      - db
      - inference
    env_file:
      - main/.env.dist
    ports:
      - "8000:8000"

volumes:
  chroma-data:
    driver: local
